---

- name: Create folder
  file:
    path: /jenkinSlave/conf
    state: directory

- name: Create folder
  file:
    path: /jenkinSlave/data
    state: directory
    owner: 65534
    group: 65534
        
- name: Generate docker-compose
  template:
    src: docker-compose.j2
    dest: "{{ docker_folder }}/docker-compose.yml"
    
- name: Generate Service's template
  template:
    src: jenkinSlave.service.j2
    dest: /etc/systemd/system/jenkinSlave.service

- name: restart jenkinSlave service
  systemd:
    state: restarted
    daemon_reload: yes
    name: jenkinSlave